export const GET_USER_INFO_REQUEST = 'GET_USER_INFO_REQUEST'
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS'
export const GET_USER_INFO_FAILURE = 'GET_USER_INFO_FAILURE'

export const GET_ALL_USERS_REQUEST = 'GET_ALL_USERS_REQUEST'
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS'
export const GET_ALL_USERS_FAILURE = 'GET_ALL_USERS_FAILURE'

export const COMMIT_TRANSACTION_REQUEST = 'COMMIT_TRANSACTION_REQUEST'
export const COMMIT_TRANSACTION_SUCCESS = 'COMMIT_TRANSACTION_SUCCESS'
export const COMMIT_TRANSACTION_ERROR = 'COMMIT_TRANSACTION_ERROR'
